# Generated by Django 2.2.7 on 2020-02-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название ')),
                ('price', models.IntegerField(db_index=True, default=0, verbose_name='Цена')),
            ],
        ),
    ]
