# Generated by Django 2.2.7 on 2020-02-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
